// THE CONTRACT. Only the Architect edits this file, as its own "CONTRACT: ..." commit on
// integration. Pure TypeScript: no DOM types, no package imports, no runtime behavior
// beyond a few constant tables. Every lane compiles against it.
//
// Conventions
// - Pixel coordinates (Px) are in the *working raster* of the map (MapImage.width/height),
//   origin top-left, x right, y down. Features and anchors store pixels; lat/lon is derived
//   through a GeoFit at display/export time.
// - LatLon is [lat, lon] in WGS84 degrees (the prototype's order). Writers that need
//   lon,lat (KML, GeoJSON) swap on output.
// - Distances are meters unless a name says otherwise (…Px for pixels).
// - All contract data is plain, structured-clone-safe JSON-like data (no class instances,
//   no functions) except where a member is explicitly a callback or command object.

/* ================================================================ primitives */

/** A point in working-raster pixel coordinates: [x, y]. */
export type Px = readonly [x: number, y: number];

/** A WGS84 position in degrees: [lat, lon]. */
export type LatLon = readonly [lat: number, lon: number];

/** An 8-bit RGB color, each channel 0..255 (may be fractional mid-computation). */
export type Rgb = readonly [r: number, g: number, b: number];

/** A CSS hex color, "#rrggbb" lower- or upper-case. */
export type HexColor = string;

/** Opaque string ids. Generated by the state layer (src/state), unique within a project. */
export type AnchorId = string;
/** Id of a Feature (trail, POI or area). */
export type FeatureId = string;
/** Id of an auto-trace color chip. */
export type ChipId = string;
/** Id of an auto-trace candidate line (not persisted). */
export type CandidateId = string;
/** Handle for a raster held inside the worker (see WorkerApi.loadImage). */
export type ImageId = string;
/** Caller-chosen id for a worker job, used by WorkerApi.cancel. */
export type JobId = string;

/** Length units shown in the UI and written into export descriptions. */
export type Units = 'mi' | 'km';

/** An RGBA raster, row-major, 4 bytes per pixel. Structurally compatible with DOM ImageData. */
export interface RasterImage {
  /** Width in pixels. */
  readonly width: number;
  /** Height in pixels. */
  readonly height: number;
  /** RGBA bytes, length = width * height * 4. */
  readonly data: Uint8ClampedArray;
}

/* ================================================================ map image */

/** Where the working raster came from. */
export type MapSource =
  /** A bitmap file (PNG/JPG/WebP/…); mimeType is the original file's type. */
  | { readonly kind: 'image'; readonly mimeType: string }
  /** One page of a PDF rendered to a bitmap at renderScale (PDF points -> pixels). */
  | { readonly kind: 'pdf'; readonly page: number; readonly pageCount: number; readonly renderScale: number };

/** Metadata about the map image a project traces over. The pixels themselves live outside the project JSON. */
export interface MapImage {
  /** Display name, usually the file name without extension. */
  readonly fileName: string;
  /** Working raster width in pixels (the coordinate space of every Px). */
  readonly width: number;
  /** Working raster height in pixels. */
  readonly height: number;
  /** Width of the original image before the working-resolution cap (== width if not scaled). */
  readonly originalWidth: number;
  /** Height of the original image before the working-resolution cap. */
  readonly originalHeight: number;
  /** Origin of the raster. */
  readonly source: MapSource;
  /** Lower-case hex SHA-256 of the original file bytes; lets autosave/project files verify the image. */
  readonly sha256: string;
  /**
   * Imagery credit for maps captured from an imagery service (T-318/T-320), e.g.
   * "Imagery: USDA NAIP via USGS The National Map". Shown in the app and written into KML/KMZ.
   * Absent for maps opened from a file.
   */
  readonly attribution?: string;
  /** Year the imagery was acquired, when the provider reports it (NAIP, T-320). */
  readonly acquisitionYear?: number;
}

/** Longest side, in pixels, of the working raster. Larger images are downscaled for tracing; the original is kept for export. */
export const MAX_WORKING_SIDE = 7000;

/* ================================================================ anchors & fit */

/** How an anchor's real-world position was entered. */
export type AnchorSource = 'paste' | 'basemap';

/** A ground control point: a pixel on the map tied to a real-world position. */
export interface Anchor {
  /** Stable id. */
  readonly id: AnchorId;
  /** Location on the map image. */
  readonly px: Px;
  /** Real-world position, or null while the user has placed the pin but not entered coordinates. */
  readonly ll: LatLon | null;
  /** How ll was entered (M2 adds 'basemap'). */
  readonly source: AnchorSource;
}

/** Fit method requested by the user. 'auto' = affine with >= 4 anchors, else similarity (prototype rule). */
export type FitMethod = 'auto' | 'similarity' | 'affine' | 'tps';

/** Fit method actually used after fallbacks (e.g. TPS with < 4 anchors falls back to affine). */
export type ResolvedFitMethod = Exclude<FitMethod, 'auto'>;

/**
 * Local planar frame the fit is solved in (prototype Core.fit): pixels are normalized
 * u = (x - cx) / scale, v = (y - cy) / scale; geography is local east/north meters
 * E = (lon - lon0) * kx, N = (lat - lat0) * ky around the anchor centroid.
 */
export interface FitFrame {
  /** Latitude of the anchor centroid (degrees). */
  readonly lat0: number;
  /** Longitude of the anchor centroid (degrees). */
  readonly lon0: number;
  /** Meters per degree of longitude at lat0. */
  readonly kx: number;
  /** Meters per degree of latitude. */
  readonly ky: number;
  /** Pixel x of the normalization center (image width / 2). */
  readonly cx: number;
  /** Pixel y of the normalization center (image height / 2). */
  readonly cy: number;
  /** Pixel normalization scale (max(width, height)). */
  readonly scale: number;
}

/** Row-major 2x3 affine map from normalized (u, v) to (E, N): E = m[0]u + m[1]v + m[2], N = m[3]u + m[4]v + m[5]. */
export type Affine2x3 = readonly [number, number, number, number, number, number];

/** The solved transform. Serializable so it can cross the worker boundary and be cached. */
export type FitModel =
  /** Similarity (scale + rotation + translation, no mirroring), stored as its equivalent affine. */
  | { readonly kind: 'similarity'; readonly affine: Affine2x3 }
  /** Least-squares affine. */
  | { readonly kind: 'affine'; readonly affine: Affine2x3 }
  /**
   * Thin-plate spline with r^2 log r^2 kernel in normalized coordinates.
   * weightsE/weightsN have length controls.length + 3: kernel weights then [a0, au, av].
   */
  | {
      readonly kind: 'tps';
      readonly controls: readonly (readonly [u: number, v: number])[];
      readonly weightsE: readonly number[];
      readonly weightsN: readonly number[];
      /** Best-fit affine of the same anchors; used for inverse seeding and residual checks. */
      readonly affine: Affine2x3;
    };

/** A successful georeference: everything needed to map pixels to lat/lon and judge quality. */
export interface GeoFit {
  /** Discriminant. */
  readonly ok: true;
  /** Method the user asked for. */
  readonly requested: FitMethod;
  /** Method actually used. */
  readonly method: ResolvedFitMethod;
  /** Normalization frame. */
  readonly frame: FitFrame;
  /** Solved transform. */
  readonly model: FitModel;
  /** Number of anchors with coordinates that went into the fit. */
  readonly anchorCount: number;
  /**
   * Per-anchor residual in meters. For TPS these come from the companion affine
   * (a TPS interpolates exactly, so its own residuals are zero) — prototype behavior.
   */
  readonly residuals: Readonly<Record<AnchorId, number>>;
  /** Root-mean-square of residuals, meters. */
  readonly rms: number;
  /** True when there are more anchors than the model's degrees of freedom need, so residuals mean something. */
  readonly checked: boolean;
  /** Leave-one-out residuals in meters (each anchor predicted by a fit of the others). Null until computed (M2). */
  readonly looResiduals: Readonly<Record<AnchorId, number>> | null;
  /** Ground meters per working-raster pixel (geometric mean scale). */
  readonly metersPerPixel: number;
  /** True when the anchors describe a mirror image (e.g. lat/lon swapped on one anchor). */
  readonly mirrored: boolean;
  /** True when metersPerPixel is outside PLAUSIBLE_METERS_PER_PIXEL. */
  readonly implausibleScale: boolean;
}

/** Why a fit could not be produced. */
export interface FitFailure {
  /** Discriminant. */
  readonly ok: false;
  /** 'too-few': fewer than 2 anchors with coordinates. 'degenerate': anchors coincide or are collinear for the method. */
  readonly reason: 'too-few' | 'degenerate';
  /** Anchors with coordinates that were available. */
  readonly anchorCount: number;
  /** How many more anchors with coordinates are needed (0 when degenerate). */
  readonly need: number;
}

/** Result of fitting anchors. */
export type FitResult = GeoFit | FitFailure;

/** Plausible park-map scale range in meters per pixel (prototype: warn outside 0.005..200). */
export const PLAUSIBLE_METERS_PER_PIXEL = { min: 0.005, max: 200 } as const;

/** Residual above which an anchor is flagged as the odd one out: max(OUTLIER_MIN_M, rms * OUTLIER_RMS_FACTOR). */
export const OUTLIER_MIN_M = 25;
/** See OUTLIER_MIN_M. */
export const OUTLIER_RMS_FACTOR = 2.2;

/* ================================================================ features */

/** Point-of-interest categories; each maps to a GPX <sym> and a KML icon in src/core/export. */
export const POI_TYPES = [
  'Trailhead',
  'Parking',
  'Restroom',
  'Viewpoint',
  'Campsite',
  'Water',
  'Information',
  'Junction',
  'Waypoint',
] as const;

/** One of POI_TYPES. */
export type PoiType = (typeof POI_TYPES)[number];

/** Fields every feature has. */
export interface FeatureBase {
  /** Stable id. */
  readonly id: FeatureId;
  /** User-visible name. */
  readonly name: string;
  /** Display and export color. */
  readonly color: HexColor;
  /** Free-text notes, exported as description. */
  readonly notes: string;
}

/** A traced trail: an open polyline. */
export interface Trail extends FeatureBase {
  /** Discriminant. */
  readonly kind: 'trail';
  /** Vertices in order, length >= 2. */
  readonly pts: readonly Px[];
  /** Ink color the trail was traced along (for smart "continue"), or null if drawn by hand. */
  readonly ink: Rgb | null;
}

/** A point of interest. */
export interface Poi extends FeatureBase {
  /** Discriminant. */
  readonly kind: 'poi';
  /** Location. */
  readonly at: Px;
  /** Category. */
  readonly poiType: PoiType;
}

/** A closed area (polygon). pts is the open ring; the closing edge is implied. */
export interface Area extends FeatureBase {
  /** Discriminant. */
  readonly kind: 'area';
  /** Ring vertices without repeating the first, length >= 3. */
  readonly pts: readonly Px[];
}

/** Any traced feature. */
export type Feature = Trail | Poi | Area;

/** Feature discriminant values. */
export type FeatureKind = Feature['kind'];

/** Default colors (prototype): trail, area, POI. */
export const DEFAULT_COLORS = { trail: '#D9480F', area: '#3A7D44', poi: '#1F6FB2' } as const;

/* ================================================================ project */

/** A trail color the user wants auto-trace to follow. */
export interface ColorChip {
  /** Stable id. */
  readonly id: ChipId;
  /** Ink color on the map. */
  readonly rgb: Rgb;
  /** Name used for candidate trails (legend name or color name). */
  readonly name: string;
  /** Whether auto-trace uses this chip. */
  readonly enabled: boolean;
  /** Share of map pixels in this color (from a scan), or null when picked by hand. */
  readonly share: number | null;
  /** True when name came from the user or a legend (candidate names then use "(part n)"). */
  readonly named: boolean;
}

/** Tracing settings persisted with the project. */
export interface TraceSettings {
  /** Smart follow on/off for the trail tool. */
  readonly smartFollow: boolean;
  /** Color distance tolerance (Euclidean RGB, 0..442), prototype default 60. */
  readonly tolerance: number;
  /** User-picked ink to follow, or null to pick from the first click (prototype "autoInk"). */
  readonly ink: Rgb | null;
}

/** Auto-trace settings persisted with the project. */
export interface AutoTraceSettings {
  /** Colors to trace. */
  readonly chips: readonly ColorChip[];
  /** Max gap in pixels to bridge between line ends (dashes, crossings); 0 = off. Default round(max(W,H)/80) clamped 6..120. */
  readonly gapPx: number;
  /** Minimum candidate length as a percentage of max(W, H). Default 4. */
  readonly minLengthPct: number;
}

/** Current project schema version. Bump with a migration in src/core/project. v2 (D-024): v1 plus an optional imported.gpx zip entry. */
export const PROJECT_VERSION = 2;

/** Everything the user has made for one map. Serializable; the map pixels are stored alongside, not inside. */
export interface Project {
  /** Schema version, equals PROJECT_VERSION after migration. */
  readonly version: typeof PROJECT_VERSION;
  /** Project name (export document name). */
  readonly name: string;
  /** The map this project traces. */
  readonly image: MapImage;
  /** Ground control points in creation order (the UI numbers them 1..n). */
  readonly anchors: readonly Anchor[];
  /** Requested fit method. */
  readonly fitMethod: FitMethod;
  /** Traced features in creation order. */
  readonly features: readonly Feature[];
  /** Display/export units. */
  readonly units: Units;
  /** Manual/smart tracing settings. */
  readonly trace: TraceSettings;
  /** Auto-trace settings. */
  readonly autoTrace: AutoTraceSettings;
  /** Next value of the id sequence used by the state layer. */
  readonly seq: number;
  /** ISO-8601 time of last modification. */
  readonly updatedAt: string;
}

/* ================================================================ history */

/**
 * An undoable edit. Every change to Project goes through one. apply/revert are pure:
 * revert(apply(p)) must deep-equal p, which is what makes undo/redo exact.
 */
export interface HistoryCommand {
  /** Short user-visible label, e.g. "Move vertex", shown as "Undo Move vertex". */
  readonly label: string;
  /** Returns the project with the edit applied. */
  apply(project: Project): Project;
  /** Returns the project with the edit undone. */
  revert(project: Project): Project;
  /** Consecutive commands with the same non-null key (e.g. typing a name) coalesce into one undo step. */
  readonly coalesceKey: string | null;
}

/** Max undo depth (prototype: 120). */
export const HISTORY_LIMIT = 120;

/* ================================================================ tracing */

/** Options shared by the color-following tools. */
export interface TraceOptions {
  /** Color distance tolerance, Euclidean RGB. */
  readonly tolerance: number;
}

/** One smart-follow hop: least-cost path from `from` to `to` preferring pixels near `ink`. */
export interface SmartTraceRequest extends TraceOptions {
  /** Raster to trace on (worker handle). */
  readonly imageId: ImageId;
  /** Start of the hop (the draft's last vertex; not re-snapped). */
  readonly from: Px;
  /** Where the user clicked; snapped to ink within snapRadiusPx first. */
  readonly to: Px;
  /** Ink color to follow. */
  readonly ink: Rgb;
  /** Snap radius in pixels (prototype: 8 screen px / zoom, clamped 2..30). */
  readonly snapRadiusPx: number;
}

/** Result of a smart-follow hop. */
export interface SmartTraceResult {
  /** Path from `from` to `snappedTo` inclusive, simplified (Douglas-Peucker 0.9 px); null if the hop was too large or unreachable. */
  readonly path: readonly Px[] | null;
  /** The click after snapping to ink (== request.to when nothing matched). */
  readonly snappedTo: Px;
  /** Wall time spent in the worker, ms. */
  readonly ms: number;
}

/** A color the scan found drawn as thin lines. */
export interface ScannedColor {
  /** Mean color of the cluster. */
  readonly rgb: Rgb;
  /** Human color name from nameColor (e.g. "Blue"). */
  readonly name: string;
  /** Fraction of sampled pixels in this cluster. */
  readonly share: number;
  /** Edge pixels / cluster pixels; high means thin strokes. */
  readonly thinness: number;
  /** HSL saturation 0..1. */
  readonly saturation: number;
  /** HSL lightness 0..1. */
  readonly lightness: number;
  /** Ranking score (prototype: share * thinness * (0.35 + saturation)). */
  readonly score: number;
  /** True when it looks like a trail color and should be pre-ticked. */
  readonly likely: boolean;
}

/** Output of a color scan, best first, at most 10 colors. */
export interface ColorScanResult {
  /** Candidate trail colors. */
  readonly colors: readonly ScannedColor[];
}

/** Auto-trace one or more colors into candidate lines. */
export interface AutoTraceRequest extends TraceOptions {
  /** Raster to trace (worker handle). */
  readonly imageId: ImageId;
  /** Colors to trace, each producing its own candidates. */
  readonly colors: readonly { readonly chipId: ChipId; readonly rgb: Rgb }[];
  /** Gap bridging distance in pixels (0 = off). */
  readonly gapPx: number;
  /** Candidates shorter than this (pixels) are dropped. */
  readonly minLengthPx: number;
  /** M2: join candidates of different colors that continue each other (a trail that changes color). Default false. */
  readonly mergeAcrossColors?: boolean;
}

/** A line found by auto-trace, awaiting user review. */
export interface AutoTraceCandidate {
  /** Id unique within one auto-trace result. */
  readonly id: CandidateId;
  /** Chip whose color produced it. */
  readonly chipId: ChipId;
  /** Polyline, simplified. */
  readonly pts: readonly Px[];
  /** Length in pixels. */
  readonly lengthPx: number;
  /** Ink color traced. */
  readonly ink: Rgb;
  /** 0..1 confidence that this is a real trail (M2); null until implemented. */
  readonly confidence: number | null;
  /** M2: other chips whose lines were merged into this candidate (mergeAcrossColors); absent or empty otherwise. */
  readonly alsoChips?: readonly ChipId[];
}

/**
 * Hooks passed into long-running core functions. Core calls progress() at stage
 * boundaries and at least every ~50 ms of work, and calls throwIfCancelled() at least
 * that often; it throws a JobCancelledError to abort.
 */
export interface JobHooks {
  /** Report progress: fraction 0..1 of the whole job, and a short stage label. */
  progress(fraction: number, stage: string): void;
  /** Throws JobCancelledError if the job was cancelled. */
  throwIfCancelled(): void;
}

/** Name of the error thrown when a job is cancelled (Error.name === JOB_CANCELLED). */
export const JOB_CANCELLED = 'JobCancelled';

/* ================================================================ topology (M2) */

/** Options for snapping trail ends to nearby trails. */
export interface SnapOptions {
  /** Max distance in working-raster pixels an end may move to meet another trail. */
  readonly tolerancePx: number;
}

/** Result of topology cleanup: the features to replace, by id. */
export interface TopologyEdit {
  /** Features after the edit (same ids as before where they survived). */
  readonly updated: readonly Feature[];
  /** Ids of features removed (e.g. merged by a join). */
  readonly removed: readonly FeatureId[];
}

/* ================================================================ export */

/** A feature resolved to real-world coordinates, ready for writers. */
export type GeoFeature =
  | (Trail & { readonly ll: readonly LatLon[]; readonly lengthM: number })
  | (Area & { readonly ll: readonly LatLon[]; readonly lengthM: number })
  | (Poi & { readonly ll: LatLon });

/** Input to every writer. Built from a Project and a GeoFit by toExportDocument. */
export interface ExportDocument {
  /** Document name. */
  readonly name: string;
  /** Features in export order (trails, areas, POIs). */
  readonly features: readonly GeoFeature[];
}

/** Writer options. */
export interface ExportOptions {
  /** Units for lengths in descriptions. */
  readonly units: Units;
  /** ISO-8601 timestamp for GPX <metadata><time>; injectable so output is deterministic in tests. */
  readonly time: string;
}

/** Export file formats. */
export type ExportFormat = 'gpx' | 'kml' | 'kmz' | 'geojson';

/** The map image drawn as a KML GroundOverlay. */
export interface KmlOverlay {
  /** Href inside the KMZ, e.g. "files/map.jpg". */
  readonly href: string;
  /** Corners as gx:LatLonQuad order: bottom-left, bottom-right, top-right, top-left. */
  readonly quad: readonly [LatLon, LatLon, LatLon, LatLon];
}

/** Everything needed to build a KMZ (runs in the worker). */
export interface KmzRequest {
  /** Features to write. */
  readonly doc: ExportDocument;
  /** Writer options. */
  readonly options: ExportOptions;
  /** Encoded overlay image bytes (JPEG, long side <= 4096 px), or null for no overlay. */
  readonly overlayImage: { readonly bytes: Uint8Array; readonly ext: 'jpg' | 'png' } | null;
  /** Overlay corners (from overlayQuad); required when overlayImage is set. */
  readonly quad: KmlOverlay['quad'] | null;
}

/* ================================================================ worker */

/** Progress event delivered to the main thread. */
export interface JobProgress {
  /** Job this refers to. */
  readonly jobId: JobId;
  /** 0..1. */
  readonly fraction: number;
  /** Short stage label, e.g. "Thinning". */
  readonly stage: string;
}

/** Per-call job control. onProgress crosses the worker boundary as a Comlink proxy. */
export interface JobControl {
  /** Caller-chosen id; pass to WorkerApi.cancel. */
  readonly jobId: JobId;
  /** Optional progress callback. */
  readonly onProgress?: (p: JobProgress) => void;
}

/**
 * Everything the worker exposes (Comlink). Heavy jobs are cancellable: cancel(jobId)
 * makes the pending promise reject with an Error named JOB_CANCELLED within 100 ms.
 * Rasters are transferred once with loadImage and stay in the worker.
 */
export interface WorkerApi {
  /** Take ownership of a raster (transfer its buffer); returns a handle for later jobs. */
  loadImage(image: RasterImage): Promise<ImageId>;
  /** Free a raster. */
  releaseImage(id: ImageId): Promise<void>;
  /** Dominant ink color near a click (prototype pickInk). radiusPx is clamped 1..14. */
  pickInk(id: ImageId, at: Px, radiusPx: number): Promise<Rgb>;
  /** Nearest pixel matching ink within radius, or null (prototype snap). */
  snapToInk(id: ImageId, at: Px, ink: Rgb, tolerance: number, radiusPx: number): Promise<Px | null>;
  /** One smart-follow hop. */
  smartTrace(req: SmartTraceRequest, ctl: JobControl): Promise<SmartTraceResult>;
  /** Find colors drawn as thin lines. */
  scanColors(id: ImageId, ctl: JobControl): Promise<ColorScanResult>;
  /** Auto-trace candidate lines for the given colors. */
  autoTrace(req: AutoTraceRequest, ctl: JobControl): Promise<readonly AutoTraceCandidate[]>;
  /** Build a KMZ archive (doc.kml + overlay image). */
  buildKmz(req: KmzRequest, ctl: JobControl): Promise<Uint8Array>;
  /** Cancel a running or queued job; no-op if unknown or finished. */
  cancel(jobId: JobId): Promise<void>;
}
